name: mi_card1
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - images/
  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Silkscreen
      fonts:
         - asset: fonts/Silkscreen-Regular.ttf
    - family: Lobs
      fonts:
         - asset: fonts/Lobster-Regular.ttf
    - family: Bungee
      fonts:
         - asset: fonts/BungeeSpice-Regular.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf